// generated by build.rs
use crate::error;
use serde::Deserialize;
use serde::Serialize;
use wasm_bindgen::prelude::wasm_bindgen;
#[wasm_bindgen]
#[derive(Serialize, Deserialize, Hash, Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u32)]
pub enum Kind {
        Armor = 0,    SunCore = 1,    PlasmaCargo = 2,    ElectroFieldLauncher = 3,    PlasmaRawDepot = 4,    IronAsteroid = 5,    CoalCargo = 6,    Static = 7,    Generator = 8,    PlasmaElectroFieldCollector = 9,    Core = 10,    IceCargo = 11,    PlasmaRefineryOutput = 12,    IceCollector = 13,    Target = 14,    IceAsteroid = 15,    CoalDepot = 16,    IronOreCargo = 17,    IronOreCollector = 18,    WaterCollector = 19,    Luciole = 20,    IronCollector = 21,    EnergyCollector = 22,    IronOreDepot = 23,    IceMelter = 24,    Flower = 25,    HeatCollector = 26,    Battery = 27,    Booster = 28,    Light = 29,    PlasmaRawCollector = 30,    IronFurnace = 31,    EnergyCargo = 32,    Water = 33,    CoalAsteroid = 34,    CoalCollector = 35,    IronGangueCollector = 36,    EnergyDepot = 37,    Anchor = 38,    Sun = 39,    PlasmaRefineryInput = 40,    Cargo = 41,
}
pub fn kindstr_to_kind(x: &str) -> Kind {
    match x.trim().to_lowercase().as_str() {
            "armor" => Kind::Armor,    "sun_core" => Kind::SunCore,    "plasma_cargo" => Kind::PlasmaCargo,    "electro_field_launcher" => Kind::ElectroFieldLauncher,    "plasma_raw_depot" => Kind::PlasmaRawDepot,    "iron_asteroid" => Kind::IronAsteroid,    "coal_cargo" => Kind::CoalCargo,    "static" => Kind::Static,    "generator" => Kind::Generator,    "plasma_electro_field_collector" => Kind::PlasmaElectroFieldCollector,    "core" => Kind::Core,    "ice_cargo" => Kind::IceCargo,    "plasma_refinery_output" => Kind::PlasmaRefineryOutput,    "ice_collector" => Kind::IceCollector,    "target" => Kind::Target,    "ice_asteroid" => Kind::IceAsteroid,    "coal_depot" => Kind::CoalDepot,    "iron_ore_cargo" => Kind::IronOreCargo,    "iron_ore_collector" => Kind::IronOreCollector,    "water_collector" => Kind::WaterCollector,    "luciole" => Kind::Luciole,    "iron_collector" => Kind::IronCollector,    "energy_collector" => Kind::EnergyCollector,    "iron_ore_depot" => Kind::IronOreDepot,    "ice_melter" => Kind::IceMelter,    "flower" => Kind::Flower,    "heat_collector" => Kind::HeatCollector,    "battery" => Kind::Battery,    "booster" => Kind::Booster,    "light" => Kind::Light,    "plasma_raw_collector" => Kind::PlasmaRawCollector,    "iron_furnace" => Kind::IronFurnace,    "energy_cargo" => Kind::EnergyCargo,    "water" => Kind::Water,    "coal_asteroid" => Kind::CoalAsteroid,    "coal_collector" => Kind::CoalCollector,    "iron_gangue_collector" => Kind::IronGangueCollector,    "energy_depot" => Kind::EnergyDepot,    "anchor" => Kind::Anchor,    "sun" => Kind::Sun,    "plasma_refinery_input" => Kind::PlasmaRefineryInput,    "cargo" => Kind::Cargo,
        _ => {
            let m = format!("invalid kind: {x}");
            error(&m);
            panic!("{}",m)
        }
    }
}
impl Kind {
    pub fn is_static(self) -> bool {
        matches!(
            self,
            Kind::Static|Kind::IronFurnace
        )
    }
}
