flowchart LR
  ice_asteroid -.->|ice| ice_collector
  ice_cargo -.->|ice| ice_collector
  ice_collector -.->|ice| ice_cargo
  ice_collector -.->|ice| ice_melter
  water -.->|water| luciole
  ice_melter -.->|water| water_collector
  water_collector -.->|water| generator
  water -.->|water| flower
  flower -.->|nectar| luciole
  coal_collector -.->|coal| coal_depot
  coal_depot -.->|coal| iron_furnace
  coal_depot -.->|coal| coal_depot
  coal_asteroid -.->|coal| coal_collector
  coal_collector -.->|coal| coal_cargo
  coal_cargo -.->|coal| coal_collector
  iron_asteroid -.->|iron_ore| iron_ore_collector
  iron_ore_collector -.->|iron_ore| iron_ore_depot
  iron_ore_collector -.->|iron_ore| iron_ore_cargo
  iron_ore_cargo -.->|iron_ore| iron_ore_collector
  iron_ore_depot -.->|iron_ore| iron_furnace
  iron_ore_depot -.->|iron_ore| iron_ore_depot
  iron_furnace -.->|iron| iron_collector
  iron_furnace -.->|iron_gangue| iron_gangue_collector
  heat_collector -.->|heat| generator
  iron_furnace -.->|heat| heat_collector
  generator -.->|energy| energy_depot
  energy_collector -.->|energy| battery
  energy_collector -.->|energy| energy_cargo
  energy_cargo -.->|energy| energy_collector
  energy_cargo -.->|energy| energy_cargo
  core -.->|energy| booster
  battery -.->|energy| ice_melter
  battery -.->|energy| booster
  energy_depot -.->|energy| energy_collector
  core -.->|energy| energy_cargo
  core -.->|energy| energy_collector
  battery -.->|energy| battery
