version: "3"
services:
    front_deployed:
        image: nginx
        ports:
            - 81:80
        volumes:
            - $HOME/github.com/loicbourgois/gravitle/docs:/usr/share/nginx/html
    front:
        image: nginx
        ports:
            - 82:80
        volumes:
            - $HOME/github.com/loicbourgois/gravitle/front:/usr/share/nginx/html
