// generated by build.rs
const Kind = {
  __KIND__
}
const kinds = [
  __KINDS__
]
export {
    Kind,
    kinds,
}

// [
//   'small_ship', 'plasma_collector', 'sun', 'plasma_depot', 
//   'harvester', 'plasma_refinery', 'plasma_transporter',
//   'ice_asteroid', "iron_asteroid", "coal_asteroid", 'chain_reaction', 'iron_furnace'
// ]