/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_gravithrust_free(a: number): void;
export function __wbg_get_gravithrust_diameter(a: number): number;
export function __wbg_set_gravithrust_diameter(a: number, b: number): void;
export function __wbg_get_gravithrust_points(a: number): number;
export function __wbg_set_gravithrust_points(a: number, b: number): void;
export function __wbg_get_gravithrust_step(a: number): number;
export function __wbg_set_gravithrust_step(a: number, b: number): void;
export function __wbg_get_gravithrust_sub_steps(a: number): number;
export function __wbg_set_gravithrust_sub_steps(a: number, b: number): void;
export function __wbg_get_gravithrust_max_rotation_speed(a: number): number;
export function __wbg_set_gravithrust_max_rotation_speed(a: number, b: number): void;
export function __wbg_get_gravithrust_max_speed_at_target(a: number): number;
export function __wbg_set_gravithrust_max_speed_at_target(a: number, b: number): void;
export function __wbg_get_gravithrust_forward_max_speed(a: number): number;
export function __wbg_set_gravithrust_forward_max_speed(a: number, b: number): void;
export function __wbg_get_gravithrust_forward_max_angle(a: number): number;
export function __wbg_set_gravithrust_forward_max_angle(a: number, b: number): void;
export function __wbg_get_gravithrust_slow_down_max_angle(a: number): number;
export function __wbg_set_gravithrust_slow_down_max_angle(a: number, b: number): void;
export function __wbg_get_gravithrust_slow_down_max_speed_to_target_ratio(a: number): number;
export function __wbg_set_gravithrust_slow_down_max_speed_to_target_ratio(a: number, b: number): void;
export function gravithrust_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function gravithrust_add_particle(a: number, b: number, c: number, d: number, e: number): void;
export function gravithrust_add_ship(a: number, b: number, c: number): void;
export function gravithrust_particles_size(a: number): number;
export function gravithrust_particle_size(a: number): number;
export function gravithrust_particles_count(a: number): number;
export function gravithrust_particles(a: number): number;
export function gravithrust_ships_size(a: number): number;
export function gravithrust_ship_size(a: number): number;
export function gravithrust_ships_count(a: number): number;
export function gravithrust_ships(a: number): number;
export function gravithrust_ticks(a: number): void;
export function gravithrust_particle_size_(a: number): number;
export function gravithrust_ship_size_(a: number): number;
export function __wbg_vector_free(a: number): void;
export function __wbg_get_vector_x(a: number): number;
export function __wbg_set_vector_x(a: number, b: number): void;
export function __wbg_get_vector_y(a: number): number;
export function __wbg_set_vector_y(a: number, b: number): void;
export function __wbg_delta_free(a: number): void;
export function __wbg_get_delta_p(a: number): number;
export function __wbg_set_delta_p(a: number, b: number): void;
export function __wbg_get_delta_v(a: number): number;
export function __wbg_set_delta_v(a: number, b: number): void;
export function __wbg_get_delta_direction(a: number): number;
export function __wbg_set_delta_direction(a: number, b: number): void;
export function __wbg_get_delta_sid(a: number, b: number): void;
export function __wbg_set_delta_sid(a: number, b: number, c: number): void;
export function __wbg_link_free(a: number): void;
export function __wbg_shipmodel_free(a: number): void;
export function __wbg_particle_free(a: number): void;
export function __wbg_get_particle_p(a: number): number;
export function __wbg_set_particle_p(a: number, b: number): void;
export function __wbg_get_particle_v(a: number): number;
export function __wbg_set_particle_v(a: number, b: number): void;
export function __wbg_get_particle_pp(a: number): number;
export function __wbg_set_particle_pp(a: number, b: number): void;
export function __wbg_get_particle_direction(a: number): number;
export function __wbg_set_particle_direction(a: number, b: number): void;
export function __wbg_get_particle_m(a: number): number;
export function __wbg_set_particle_m(a: number, b: number): void;
export function __wbg_get_particle_k(a: number): number;
export function __wbg_set_particle_k(a: number, b: number): void;
export function __wbg_get_particle_a(a: number): number;
export function __wbg_set_particle_a(a: number, b: number): void;
export function __wbg_get_particle_grid_id(a: number): number;
export function __wbg_set_particle_grid_id(a: number, b: number): void;
export function __wbg_get_particle_idx(a: number): number;
export function __wbg_set_particle_idx(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
