const Kind = {
    Armor: 1,
    Core: 2,
    Booster: 3,
    Sun: 4,
    Light: 5,
    Plant: 6,
    Metal: 7,
    Depot: 8,
    Target: 9,
    Ray: 10,
    Cargo: 11,
    Plasma: 12,
    Field: 13,
    Anchor: 14,
    SunCore: 15,
    ElectroField: 16,
    PlasmaElectroField: 17,
    PlasmaCargo: 18,
    PlasmaCollector: 19,
    PlasmaDepot: 20,
    Static: 21,
    Default: 22,
}}
export {{
    Kind,
}}
