// generated by build.rs
const blueprint_names = [
  'chain_reaction',
  'coal_asteroid',
  'coal_collector',
  'harvester',
  'ice_asteroid',
  'iron_asteroid',
  'iron_furnace',
  'iron_ore_collector',
  'iron_ore_collector_2',
  'plasma_collector',
  'plasma_depot',
  'plasma_refinery',
  'plasma_transporter',
  'small_ship',
  'sun'
]
const job_names = [
  'coal_collector',
  'electro_field_launcher',
  'iron_ore_collector',
  'plasma_collector',
  'plasma_transporter'
]
export {
  blueprint_names,
  job_names,
}

